language: groovy
jdk:
- openjdk7
- oraclejdk8
cache:
  apt: true
  directories:
  - $HOME/.gradle/caches
install:
 - sudo apt-get install pandoc texlive-latex-base texlive-luatex r-base-core
 - ./gradlew ciPrepare
script: ./gradlew ciBuild
after_success:
- ./gradlew ciPostBuild
env:
  global:
  - TERM=dumb
  - DEPLOY_USER=ekstrand
  - secure: Z3WTzkpSiSfH985uLIfyHw2HM/+R8+qT2DzwiMbzS4g+JtxHox7sFOlLyhc2Xn+2Yl68KFkJLIl/i0EKI1kHzYhC/7xajPiOOWD5aTUsYrD8q0C+woYPFDnS22f+qjEtcK2b3eh39sl3VUweylGXfc8WrqA5U67TCWmJV9yBfEY=
